type station_info_t = {
  kanji : string;
  kana : string;
  roma : string;
  route_name : string;
} ;;

type between_stations_info_t = {
  start_station_name : string;
  end_station_name : string;
  go_through_route_name : string;
  distance : float;
  duration : int;
} ;;

let global_station_info_list = [
  {kanji="代々木上原"; kana="よよぎうえはら"; roma="yoyogiuehara"; route_name="千代田線"};
  {kanji="代々木公園"; kana="よよぎこうえん"; roma="yoyogikouen"; route_name="千代田線"};
  {kanji="明治神宮前"; kana="めいじじんぐうまえ"; roma="meijijinguumae"; route_name="千代田線"};
  {kanji="表参道"; kana="おもてさんどう"; roma="omotesandou"; route_name="千代田線"};
  {kanji="乃木坂"; kana="のぎざか"; roma="nogizaka"; route_name="千代田線"};
  {kanji="赤坂"; kana="あかさか"; roma="akasaka"; route_name="千代田線"};
  {kanji="国会議事堂前"; kana="こっかいぎじどうまえ"; roma="kokkaigijidoumae"; route_name="千代田線"};
  {kanji="霞ヶ関"; kana="かすみがせき"; roma="kasumigaseki"; route_name="千代田線"};
  {kanji="日比谷"; kana="ひびや"; roma="hibiya"; route_name="千代田線"};
  {kanji="二重橋前"; kana="にじゅうばしまえ"; roma="nijuubasimae"; route_name="千代田線"};
  {kanji="大手町"; kana="おおてまち"; roma="otemachi"; route_name="千代田線"};
  {kanji="新御茶ノ水"; kana="しんおちゃのみず"; roma="shin-ochanomizu"; route_name="千代田線"};
  {kanji="湯島"; kana="ゆしま"; roma="yushima"; route_name="千代田線"};
  {kanji="根津"; kana="ねづ"; roma="nedu"; route_name="千代田線"};
  {kanji="千駄木"; kana="せんだぎ"; roma="sendagi"; route_name="千代田線"};
  {kanji="西日暮里"; kana="にしにっぽり"; roma="nishinippori"; route_name="千代田線"};
  {kanji="町屋"; kana="まちや"; roma="machiya"; route_name="千代田線"};
  {kanji="北千住"; kana="きたせんじゅ"; roma="kitasenjyu"; route_name="千代田線"};
  {kanji="綾瀬"; kana="あやせ"; roma="ayase"; route_name="千代田線"};
  {kanji="北綾瀬"; kana="きたあやせ"; roma="kitaayase"; route_name="千代田線"};
  {kanji="浅草"; kana="あさくさ"; roma="asakusa"; route_name="銀座線"};
  {kanji="田原町"; kana="たわらまち"; roma="tawaramachi"; route_name="銀座線"};
  {kanji="稲荷町"; kana="いなりちょう"; roma="inaricho"; route_name="銀座線"};
  {kanji="上野"; kana="うえの"; roma="ueno"; route_name="銀座線"};
  {kanji="上野広小路"; kana="うえのひろこうじ"; roma="uenohirokoji"; route_name="銀座線"};
  {kanji="末広町"; kana="すえひろちょう"; roma="suehirocho"; route_name="銀座線"};
  {kanji="神田"; kana="かんだ"; roma="kanda"; route_name="銀座線"};
  {kanji="三越前"; kana="みつこしまえ"; roma="mitsukoshimae"; route_name="銀座線"};
  {kanji="日本橋"; kana="にほんばし"; roma="nihonbashi"; route_name="銀座線"};
  {kanji="京橋"; kana="きょうばし"; roma="kyobashi"; route_name="銀座線"};
  {kanji="銀座"; kana="ぎんざ"; roma="ginza"; route_name="銀座線"};
  {kanji="新橋"; kana="しんばし"; roma="shinbashi"; route_name="銀座線"};
  {kanji="虎ノ門"; kana="とらのもん"; roma="toranomon"; route_name="銀座線"};
  {kanji="溜池山王"; kana="ためいけさんのう"; roma="tameikesannou"; route_name="銀座線"};
  {kanji="赤坂見附"; kana="あかさかみつけ"; roma="akasakamitsuke"; route_name="銀座線"};
  {kanji="青山一丁目"; kana="あおやまいっちょうめ"; roma="aoyamaicchome"; route_name="銀座線"};
  {kanji="外苑前"; kana="がいえんまえ"; roma="gaienmae"; route_name="銀座線"};
  {kanji="表参道"; kana="おもてさんどう"; roma="omotesando"; route_name="銀座線"};
  {kanji="渋谷"; kana="しぶや"; roma="shibuya"; route_name="銀座線"};
  {kanji="渋谷"; kana="しぶや"; roma="shibuya"; route_name="半蔵門線"};
  {kanji="表参道"; kana="おもてさんどう"; roma="omotesandou"; route_name="半蔵門線"};
  {kanji="青山一丁目"; kana="あおやまいっちょうめ"; roma="aoyama-itchome"; route_name="半蔵門線"};
  {kanji="永田町"; kana="ながたちょう"; roma="nagatacho"; route_name="半蔵門線"};
  {kanji="半蔵門"; kana="はんぞうもん"; roma="hanzomon"; route_name="半蔵門線"};
  {kanji="九段下"; kana="くだんした"; roma="kudanshita"; route_name="半蔵門線"};
  {kanji="神保町"; kana="じんぼうちょう"; roma="jinbocho"; route_name="半蔵門線"};
  {kanji="大手町"; kana="おおてまち"; roma="otemachi"; route_name="半蔵門線"};
  {kanji="三越前"; kana="みつこしまえ"; roma="mitsukoshimae"; route_name="半蔵門線"};
  {kanji="水天宮前"; kana="すいてんぐうまえ"; roma="suitengumae"; route_name="半蔵門線"};
  {kanji="清澄白河"; kana="きよすみしらかわ"; roma="kiyosumi-shirakawa"; route_name="半蔵門線"};
  {kanji="住吉"; kana="すみよし"; roma="sumiyoshi"; route_name="半蔵門線"};
  {kanji="錦糸町"; kana="きんしちょう"; roma="kinshicho"; route_name="半蔵門線"};
  {kanji="押上"; kana="おしあげ"; roma="oshiage"; route_name="半蔵門線"};
  {kanji="中目黒"; kana="なかめぐろ"; roma="nakameguro"; route_name="日比谷線"};
  {kanji="恵比寿"; kana="えびす"; roma="ebisu"; route_name="日比谷線"};
  {kanji="広尾"; kana="ひろお"; roma="hiro"; route_name="日比谷線"};
  {kanji="六本木"; kana="ろっぽんぎ"; roma="roppongi"; route_name="日比谷線"};
  {kanji="神谷町"; kana="かみやちょう"; roma="kamiyacho"; route_name="日比谷線"};
  {kanji="霞ヶ関"; kana="かすみがせき"; roma="kasumigaseki"; route_name="日比谷線"};
  {kanji="日比谷"; kana="ひびや"; roma="hibiya"; route_name="日比谷線"};
  {kanji="銀座"; kana="ぎんざ"; roma="ginza"; route_name="日比谷線"};
  {kanji="東銀座"; kana="ひがしぎんざ"; roma="higashiginza"; route_name="日比谷線"};
  {kanji="築地"; kana="つきじ"; roma="tsukiji"; route_name="日比谷線"};
  {kanji="八丁堀"; kana="はっちょうぼり"; roma="hacchobori"; route_name="日比谷線"};
  {kanji="茅場町"; kana="かやばちょう"; roma="kayabacho"; route_name="日比谷線"};
  {kanji="人形町"; kana="にんぎょうちょう"; roma="ningyomachi"; route_name="日比谷線"};
  {kanji="小伝馬町"; kana="こでんまちょう"; roma="kodemmacho"; route_name="日比谷線"};
  {kanji="秋葉原"; kana="あきはばら"; roma="akihabara"; route_name="日比谷線"};
  {kanji="仲御徒町"; kana="なかおかちまち"; roma="nakaokachimachi"; route_name="日比谷線"};
  {kanji="上野"; kana="うえの"; roma="ueno"; route_name="日比谷線"};
  {kanji="入谷"; kana="いりや"; roma="iriya"; route_name="日比谷線"};
  {kanji="三ノ輪"; kana="みのわ"; roma="minowa"; route_name="日比谷線"};
  {kanji="南千住"; kana="みなみせんじゅ"; roma="minamisenju"; route_name="日比谷線"};
  {kanji="北千住"; kana="きたせんじゅ"; roma="kitasenju"; route_name="日比谷線"};
  {kanji="池袋"; kana="いけぶくろ"; roma="ikebukuro"; route_name="丸ノ内線"};
  {kanji="新大塚"; kana="しんおおつか"; roma="shinotsuka"; route_name="丸ノ内線"};
  {kanji="茗荷谷"; kana="みょうがだに"; roma="myogadani"; route_name="丸ノ内線"};
  {kanji="後楽園"; kana="こうらくえん"; roma="korakuen"; route_name="丸ノ内線"};
  {kanji="本郷三丁目"; kana="ほんごうさんちょうめ"; roma="hongosanchome"; route_name="丸ノ内線"};
  {kanji="御茶ノ水"; kana="おちゃのみず"; roma="ochanomizu"; route_name="丸ノ内線"};
  {kanji="淡路町"; kana="あわじちょう"; roma="awajicho"; route_name="丸ノ内線"};
  {kanji="大手町"; kana="おおてまち"; roma="otemachi"; route_name="丸ノ内線"};
  {kanji="東京"; kana="とうきょう"; roma="tokyo"; route_name="丸ノ内線"};
  {kanji="銀座"; kana="ぎんざ"; roma="ginza"; route_name="丸ノ内線"};
  {kanji="霞ヶ関"; kana="かすみがせき"; roma="kasumigaseki"; route_name="丸ノ内線"};
  {kanji="国会議事堂前"; kana="こっかいぎじどうまえ"; roma="kokkaigijidomae"; route_name="丸ノ内線"};
  {kanji="赤坂見附"; kana="あかさかみつけ"; roma="akasakamitsuke"; route_name="丸ノ内線"};
  {kanji="四ツ谷"; kana="よつや"; roma="yotsuya"; route_name="丸ノ内線"};
  {kanji="四谷三丁目"; kana="よつやさんちょうめ"; roma="yotsuyasanchome"; route_name="丸ノ内線"};
  {kanji="新宿御苑前"; kana="しんじゅくぎょえんまえ"; roma="shinjuku-gyoemmae"; route_name="丸ノ内線"};
  {kanji="新宿三丁目"; kana="しんじゅくさんちょうめ"; roma="shinjuku-sanchome"; route_name="丸ノ内線"};
  {kanji="新宿"; kana="しんじゅく"; roma="shinjuku"; route_name="丸ノ内線"};
  {kanji="西新宿"; kana="にししんじゅく"; roma="nishi-shinjuku"; route_name="丸ノ内線"};
  {kanji="中野坂上"; kana="なかのさかうえ"; roma="nakano-sakaue"; route_name="丸ノ内線"};
  {kanji="新中野"; kana="しんなかの"; roma="shin-nakano"; route_name="丸ノ内線"};
  {kanji="東高円寺"; kana="ひがしこうえんじ"; roma="higashi-koenji"; route_name="丸ノ内線"};
  {kanji="新高円寺"; kana="しんこうえんじ"; roma="shin-koenji"; route_name="丸ノ内線"};
  {kanji="南阿佐ヶ谷"; kana="みなみあさがや"; roma="minami-asagaya"; route_name="丸ノ内線"};
  {kanji="荻窪"; kana="おぎくぼ"; roma="ogikubo"; route_name="丸ノ内線"};
  {kanji="中野新橋"; kana="なかのしんばし"; roma="nakano-shimbashi"; route_name="丸ノ内線"};
  {kanji="中野富士見町"; kana="なかのふじみちょう"; roma="nakano-fujimicho"; route_name="丸ノ内線"};
  {kanji="方南町"; kana="ほうなんちょう"; roma="honancho"; route_name="丸ノ内線"};
  {kanji="四ツ谷"; kana="よつや"; roma="yotsuya"; route_name="南北線"};
  {kanji="永田町"; kana="ながたちょう"; roma="nagatacho"; route_name="南北線"};
  {kanji="溜池山王"; kana="ためいけさんのう"; roma="tameikesanno"; route_name="南北線"};
  {kanji="六本木一丁目"; kana="ろっぽんぎいっちょうめ"; roma="roppongiitchome"; route_name="南北線"};
  {kanji="麻布十番"; kana="あざぶじゅうばん"; roma="azabujuban"; route_name="南北線"};
  {kanji="白金高輪"; kana="しろかねたかなわ"; roma="shirokanetakanawa"; route_name="南北線"};
  {kanji="白金台"; kana="しろかねだい"; roma="shirokanedai"; route_name="南北線"};
  {kanji="目黒"; kana="めぐろ"; roma="meguro"; route_name="南北線"};
  {kanji="市ヶ谷"; kana="いちがや"; roma="ichigaya"; route_name="南北線"};
  {kanji="飯田橋"; kana="いいだばし"; roma="idabashi"; route_name="南北線"};
  {kanji="後楽園"; kana="こうらくえん"; roma="korakuen"; route_name="南北線"};
  {kanji="東大前"; kana="とうだいまえ"; roma="todaimae"; route_name="南北線"};
  {kanji="本駒込"; kana="ほんこまごめ"; roma="honkomagome"; route_name="南北線"};
  {kanji="駒込"; kana="こまごめ"; roma="komagome"; route_name="南北線"};
  {kanji="西ヶ原"; kana="にしがはら"; roma="nishigahara"; route_name="南北線"};
  {kanji="王子"; kana="おうじ"; roma="oji"; route_name="南北線"};
  {kanji="王子神谷"; kana="おうじかみや"; roma="ojikamiya"; route_name="南北線"};
  {kanji="志茂"; kana="しも"; roma="shimo"; route_name="南北線"};
  {kanji="赤羽岩淵"; kana="あかばねいわぶち"; roma="akabaneiwabuchi"; route_name="南北線"};
  {kanji="西船橋"; kana="にしふなばし"; roma="nishi-funabashi"; route_name="東西線"};
  {kanji="原木中山"; kana="ばらきなかやま"; roma="baraki-nakayama"; route_name="東西線"};
  {kanji="妙典"; kana="みょうでん"; roma="myoden"; route_name="東西線"};
  {kanji="行徳"; kana="ぎょうとく"; roma="gyotoku"; route_name="東西線"};
  {kanji="南行徳"; kana="みなみぎょうとく"; roma="minami-gyotoku"; route_name="東西線"};
  {kanji="浦安"; kana="うらやす"; roma="urayasu"; route_name="東西線"};
  {kanji="葛西"; kana="かさい"; roma="kasai"; route_name="東西線"};
  {kanji="西葛西"; kana="にしかさい"; roma="nishi-kasai"; route_name="東西線"};
  {kanji="南砂町"; kana="みなみすなまち"; roma="minami-sunamachi"; route_name="東西線"};
  {kanji="東陽町"; kana="とうようちょう"; roma="touyoucho"; route_name="東西線"};
  {kanji="木場"; kana="きば"; roma="kiba"; route_name="東西線"};
  {kanji="門前仲町"; kana="もんぜんなかちょう"; roma="monzen-nakacho"; route_name="東西線"};
  {kanji="茅場町"; kana="かやばちょう"; roma="kayabacho"; route_name="東西線"};
  {kanji="日本橋"; kana="にほんばし"; roma="nihonbashi"; route_name="東西線"};
  {kanji="大手町"; kana="おおてまち"; roma="otemachi"; route_name="東西線"};
  {kanji="竹橋"; kana="たけばし"; roma="takebashi"; route_name="東西線"};
  {kanji="九段下"; kana="くだんした"; roma="kudanshita"; route_name="東西線"};
  {kanji="飯田橋"; kana="いいだばし"; roma="iidabashi"; route_name="東西線"};
  {kanji="神楽坂"; kana="かぐらざか"; roma="kagurazaka"; route_name="東西線"};
  {kanji="早稲田"; kana="わせだ"; roma="waseda"; route_name="東西線"};
  {kanji="高田馬場"; kana="たかだのばば"; roma="takadanobaba"; route_name="東西線"};
  {kanji="落合"; kana="おちあい"; roma="ochiai"; route_name="東西線"};
  {kanji="中野"; kana="なかの"; roma="nakano"; route_name="東西線"};
  {roma="shinkiba"; kana="しんきば"; kanji="新木場"; route_name="有楽町線"};
  {roma="tatsumi"; kana="たつみ"; kanji="辰巳"; route_name="有楽町線"};
  {roma="toyosu"; kana="とよす"; kanji="豊洲"; route_name="有楽町線"};
  {roma="tsukishima"; kana="つきしま"; kanji="月島"; route_name="有楽町線"};
  {roma="shintomityou"; kana="しんとみちょう"; kanji="新富町"; route_name="有楽町線"};
  {roma="ginzaittyoume"; kana="ぎんざいっちょうめ"; kanji="銀座一丁目"; route_name="有楽町線"};
  {roma="yuurakutyou"; kana="ゆうらくちょう"; kanji="有楽町"; route_name="有楽町線"};
  {roma="sakuradamon"; kana="さくらだもん"; kanji="桜田門"; route_name="有楽町線"};
  {roma="nagatacho"; kana="ながたちょう"; kanji="永田町"; route_name="有楽町線"};
  {roma="koujimachi"; kana="こうじまち"; kanji="麹町"; route_name="有楽町線"};
  {roma="ichigaya"; kana="いちがや"; kanji="市ヶ谷"; route_name="有楽町線"};
  {roma="iidabashi"; kana="いいだばし"; kanji="飯田橋"; route_name="有楽町線"};
  {kanji="江戸川橋"; kana="えどがわばし"; roma="edogawabasi"; route_name="有楽町線"};
  {kanji="護国寺"; kana="ごこくじ"; roma="gokokuji"; route_name="有楽町線"};
  {kanji="東池袋"; kana="ひがしいけぶくろ"; roma="higasiikebukuro"; route_name="有楽町線"};
  {kanji="池袋"; kana="いけぶくろ"; roma="ikebukuro"; route_name="有楽町線"};
  {kanji="要町"; kana="かなめちょう"; roma="kanametyou"; route_name="有楽町線"};
  {kanji="千川"; kana="せんかわ"; roma="senkawa"; route_name="有楽町線"};
  {kanji="小竹向原"; kana="こたけむかいはら"; roma="kotakemukaihara"; route_name="有楽町線"};
  {kanji="氷川台"; kana="ひかわだい"; roma="hikawadai"; route_name="有楽町線"};
  {kanji="平和台"; kana="へいわだい"; roma="heiwadai"; route_name="有楽町線"};
  {kanji="営団赤塚"; kana="えいだんあかつか"; roma="eidanakakuka"; route_name="有楽町線"};
  {kanji="営団成増"; kana="えいだんなります"; roma="eidannarimasu"; route_name="有楽町線"};
  {kanji="和光市"; kana="わこうし"; roma="wakousi"; route_name="有楽町線"};
]

let global_between_stations_info_list = [
  {start_station_name="代々木上原"; end_station_name="代々木公園"; go_through_route_name="千代田線"; distance=1.0; duration=2};
  {start_station_name="代々木公園"; end_station_name="明治神宮前"; go_through_route_name="千代田線"; distance=1.2; duration=2};
  {start_station_name="明治神宮前"; end_station_name="表参道"; go_through_route_name="千代田線"; distance=0.9; duration=2};
  {start_station_name="表参道"; end_station_name="乃木坂"; go_through_route_name="千代田線"; distance=1.4; duration=3};
  {start_station_name="乃木坂"; end_station_name="赤坂"; go_through_route_name="千代田線"; distance=1.1; duration=2};
  {start_station_name="赤坂"; end_station_name="国会議事堂前"; go_through_route_name="千代田線"; distance=0.8; duration=1};
  {start_station_name="国会議事堂前"; end_station_name="霞ヶ関"; go_through_route_name="千代田線"; distance=0.7; duration=1};
  {start_station_name="霞ヶ関"; end_station_name="日比谷"; go_through_route_name="千代田線"; distance=1.2; duration=2};
  {start_station_name="日比谷"; end_station_name="二重橋前"; go_through_route_name="千代田線"; distance=0.7; duration=1};
  {start_station_name="二重橋前"; end_station_name="大手町"; go_through_route_name="千代田線"; distance=0.7; duration=1};
  {start_station_name="大手町"; end_station_name="新御茶ノ水"; go_through_route_name="千代田線"; distance=1.3; duration=2};
  {start_station_name="新御茶ノ水"; end_station_name="湯島"; go_through_route_name="千代田線"; distance=1.2; duration=2};
  {start_station_name="湯島"; end_station_name="根津"; go_through_route_name="千代田線"; distance=1.2; duration=2};
  {start_station_name="根津"; end_station_name="千駄木"; go_through_route_name="千代田線"; distance=1.0; duration=2};
  {start_station_name="千駄木"; end_station_name="西日暮里"; go_through_route_name="千代田線"; distance=0.9; duration=1};
  {start_station_name="西日暮里"; end_station_name="町屋"; go_through_route_name="千代田線"; distance=1.7; duration=2};
  {start_station_name="町屋"; end_station_name="北千住"; go_through_route_name="千代田線"; distance=2.6; duration=3};
  {start_station_name="北千住"; end_station_name="綾瀬"; go_through_route_name="千代田線"; distance=2.5; duration=3};
  {start_station_name="綾瀬"; end_station_name="北綾瀬"; go_through_route_name="千代田線"; distance=2.1; duration=4};
  {start_station_name="浅草"; end_station_name="田原町"; go_through_route_name="銀座線"; distance=0.8; duration=2};
  {start_station_name="田原町"; end_station_name="稲荷町"; go_through_route_name="銀座線"; distance=0.7; duration=1};
  {start_station_name="稲荷町"; end_station_name="上野"; go_through_route_name="銀座線"; distance=0.7; duration=2};
  {start_station_name="上野"; end_station_name="上野広小路"; go_through_route_name="銀座線"; distance=0.5; duration=2};
  {start_station_name="上野広小路"; end_station_name="末広町"; go_through_route_name="銀座線"; distance=0.6; duration=1};
  {start_station_name="末広町"; end_station_name="神田"; go_through_route_name="銀座線"; distance=1.1; duration=2};
  {start_station_name="神田"; end_station_name="三越前"; go_through_route_name="銀座線"; distance=0.7; duration=1};
  {start_station_name="三越前"; end_station_name="日本橋"; go_through_route_name="銀座線"; distance=0.6; duration=2};
  {start_station_name="日本橋"; end_station_name="京橋"; go_through_route_name="銀座線"; distance=0.7; duration=2};
  {start_station_name="京橋"; end_station_name="銀座"; go_through_route_name="銀座線"; distance=0.7; duration=1};
  {start_station_name="銀座"; end_station_name="新橋"; go_through_route_name="銀座線"; distance=0.9; duration=2};
  {start_station_name="新橋"; end_station_name="虎ノ門"; go_through_route_name="銀座線"; distance=0.8; duration=2};
  {start_station_name="虎ノ門"; end_station_name="溜池山王"; go_through_route_name="銀座線"; distance=0.6; duration=2};
  {start_station_name="溜池山王"; end_station_name="赤坂見附"; go_through_route_name="銀座線"; distance=0.9; duration=2};
  {start_station_name="赤坂見附"; end_station_name="青山一丁目"; go_through_route_name="銀座線"; distance=1.3; duration=2};
  {start_station_name="青山一丁目"; end_station_name="外苑前"; go_through_route_name="銀座線"; distance=0.7; duration=2};
  {start_station_name="外苑前"; end_station_name="表参道"; go_through_route_name="銀座線"; distance=0.7; duration=1};
  {start_station_name="表参道"; end_station_name="渋谷"; go_through_route_name="銀座線"; distance=1.3; duration=1};
  {start_station_name="渋谷"; end_station_name="表参道"; go_through_route_name="半蔵門線"; distance=1.3; duration=2};
  {start_station_name="表参道"; end_station_name="青山一丁目"; go_through_route_name="半蔵門線"; distance=1.4; duration=2};
  {start_station_name="青山一丁目"; end_station_name="永田町"; go_through_route_name="半蔵門線"; distance=1.3; duration=2};
  {start_station_name="永田町"; end_station_name="半蔵門"; go_through_route_name="半蔵門線"; distance=1.0; duration=2};
  {start_station_name="半蔵門"; end_station_name="九段下"; go_through_route_name="半蔵門線"; distance=1.6; duration=2};
  {start_station_name="九段下"; end_station_name="神保町"; go_through_route_name="半蔵門線"; distance=0.4; duration=1};
  {start_station_name="神保町"; end_station_name="大手町"; go_through_route_name="半蔵門線"; distance=1.7; duration=3};
  {start_station_name="大手町"; end_station_name="三越前"; go_through_route_name="半蔵門線"; distance=0.7; duration=1};
  {start_station_name="三越前"; end_station_name="水天宮前"; go_through_route_name="半蔵門線"; distance=1.3; duration=2};
  {start_station_name="水天宮前"; end_station_name="清澄白河"; go_through_route_name="半蔵門線"; distance=1.7; duration=3};
  {start_station_name="清澄白河"; end_station_name="住吉"; go_through_route_name="半蔵門線"; distance=1.9; duration=3};
  {start_station_name="住吉"; end_station_name="錦糸町"; go_through_route_name="半蔵門線"; distance=1.; duration=2};
  {start_station_name="錦糸町"; end_station_name="押上"; go_through_route_name="半蔵門線"; distance=1.4; duration=2};
  {start_station_name="中目黒"; end_station_name="恵比寿"; go_through_route_name="日比谷線"; distance=1.; duration=2};
  {start_station_name="恵比寿"; end_station_name="広尾"; go_through_route_name="日比谷線"; distance=1.5; duration=3};
  {start_station_name="広尾"; end_station_name="六本木"; go_through_route_name="日比谷線"; distance=1.7; duration=3};
  {start_station_name="六本木"; end_station_name="神谷町"; go_through_route_name="日比谷線"; distance=1.5; duration=3};
  {start_station_name="神谷町"; end_station_name="霞ヶ関"; go_through_route_name="日比谷線"; distance=1.3; duration=2};
  {start_station_name="霞ヶ関"; end_station_name="日比谷"; go_through_route_name="日比谷線"; distance=1.2; duration=2};
  {start_station_name="日比谷"; end_station_name="銀座"; go_through_route_name="日比谷線"; distance=0.4; duration=1};
  {start_station_name="銀座"; end_station_name="東銀座"; go_through_route_name="日比谷線"; distance=0.4; duration=1};
  {start_station_name="東銀座"; end_station_name="築地"; go_through_route_name="日比谷線"; distance=0.6; duration=2};
  {start_station_name="築地"; end_station_name="八丁堀"; go_through_route_name="日比谷線"; distance=1.; duration=2};
  {start_station_name="八丁堀"; end_station_name="茅場町"; go_through_route_name="日比谷線"; distance=0.5; duration=1};
  {start_station_name="茅場町"; end_station_name="人形町"; go_through_route_name="日比谷線"; distance=0.9; duration=2};
  {start_station_name="人形町"; end_station_name="小伝馬町"; go_through_route_name="日比谷線"; distance=0.6; duration=1};
  {start_station_name="小伝馬町"; end_station_name="秋葉原"; go_through_route_name="日比谷線"; distance=0.9; duration=2};
  {start_station_name="秋葉原"; end_station_name="仲御徒町"; go_through_route_name="日比谷線"; distance=1.; duration=1};
  {start_station_name="仲御徒町"; end_station_name="上野"; go_through_route_name="日比谷線"; distance=0.5; duration=1};
  {start_station_name="上野"; end_station_name="入谷"; go_through_route_name="日比谷線"; distance=1.2; duration=2};
  {start_station_name="入谷"; end_station_name="三ノ輪"; go_through_route_name="日比谷線"; distance=1.2; duration=2};
  {start_station_name="三ノ輪"; end_station_name="南千住"; go_through_route_name="日比谷線"; distance=0.8; duration=2};
  {start_station_name="南千住"; end_station_name="北千住"; go_through_route_name="日比谷線"; distance=1.8; duration=3};
  {start_station_name="池袋"; end_station_name="新大塚"; go_through_route_name="丸ノ内線"; distance=1.8; duration=3};
  {start_station_name="新大塚"; end_station_name="茗荷谷"; go_through_route_name="丸ノ内線"; distance=1.2; duration=2};
  {start_station_name="茗荷谷"; end_station_name="後楽園"; go_through_route_name="丸ノ内線"; distance=1.8; duration=2};
  {start_station_name="後楽園"; end_station_name="本郷三丁目"; go_through_route_name="丸ノ内線"; distance=0.8; duration=1};
  {start_station_name="本郷三丁目"; end_station_name="御茶ノ水"; go_through_route_name="丸ノ内線"; distance=0.8; duration=1};
  {start_station_name="御茶ノ水"; end_station_name="淡路町"; go_through_route_name="丸ノ内線"; distance=0.8; duration=1};
  {start_station_name="淡路町"; end_station_name="大手町"; go_through_route_name="丸ノ内線"; distance=0.9; duration=2};
  {start_station_name="大手町"; end_station_name="東京"; go_through_route_name="丸ノ内線"; distance=0.6; duration=1};
  {start_station_name="東京"; end_station_name="銀座"; go_through_route_name="丸ノ内線"; distance=1.1; duration=2};
  {start_station_name="銀座"; end_station_name="霞ヶ関"; go_through_route_name="丸ノ内線"; distance=1.0; duration=2};
  {start_station_name="霞ヶ関"; end_station_name="国会議事堂前"; go_through_route_name="丸ノ内線"; distance=0.7; duration=1};
  {start_station_name="国会議事堂前"; end_station_name="赤坂見附"; go_through_route_name="丸ノ内線"; distance=0.9; duration=2};
  {start_station_name="赤坂見附"; end_station_name="四ツ谷"; go_through_route_name="丸ノ内線"; distance=1.3; duration=2};
  {start_station_name="四ツ谷"; end_station_name="四谷三丁目"; go_through_route_name="丸ノ内線"; distance=1.0; duration=2};
  {start_station_name="四谷三丁目"; end_station_name="新宿御苑前"; go_through_route_name="丸ノ内線"; distance=0.9; duration=1};
  {start_station_name="新宿御苑前"; end_station_name="新宿三丁目"; go_through_route_name="丸ノ内線"; distance=0.7; duration=1};
  {start_station_name="新宿三丁目"; end_station_name="新宿"; go_through_route_name="丸ノ内線"; distance=0.3; duration=1};
  {start_station_name="新宿"; end_station_name="西新宿"; go_through_route_name="丸ノ内線"; distance=0.8; duration=1};
  {start_station_name="西新宿"; end_station_name="中野坂上"; go_through_route_name="丸ノ内線"; distance=1.1; duration=2};
  {start_station_name="中野坂上"; end_station_name="新中野"; go_through_route_name="丸ノ内線"; distance=1.1; duration=2};
  {start_station_name="新中野"; end_station_name="東高円寺"; go_through_route_name="丸ノ内線"; distance=1.0; duration=1};
  {start_station_name="東高円寺"; end_station_name="新高円寺"; go_through_route_name="丸ノ内線"; distance=0.9; duration=1};
  {start_station_name="新高円寺"; end_station_name="南阿佐ヶ谷"; go_through_route_name="丸ノ内線"; distance=1.2; duration=2};
  {start_station_name="南阿佐ヶ谷"; end_station_name="荻窪"; go_through_route_name="丸ノ内線"; distance=1.5; duration=2};
  {start_station_name="中野坂上"; end_station_name="中野新橋"; go_through_route_name="丸ノ内線"; distance=1.3; duration=2};
  {start_station_name="中野新橋"; end_station_name="中野富士見町"; go_through_route_name="丸ノ内線"; distance=0.6; duration=1};
  {start_station_name="中野富士見町"; end_station_name="方南町"; go_through_route_name="丸ノ内線"; distance=1.3; duration=2};
  {start_station_name="市ヶ谷"; end_station_name="四ツ谷"; go_through_route_name="南北線"; distance=1.0; duration=2};
  {start_station_name="四ツ谷"; end_station_name="永田町"; go_through_route_name="南北線"; distance=1.3; duration=3};
  {start_station_name="永田町"; end_station_name="溜池山王"; go_through_route_name="南北線"; distance=0.9; duration=1};
  {start_station_name="溜池山王"; end_station_name="六本木一丁目"; go_through_route_name="南北線"; distance=0.9; duration=2};
  {start_station_name="六本木一丁目"; end_station_name="麻布十番"; go_through_route_name="南北線"; distance=1.2; duration=2};
  {start_station_name="麻布十番"; end_station_name="白金高輪"; go_through_route_name="南北線"; distance=1.3; duration=2};
  {start_station_name="白金高輪"; end_station_name="白金台"; go_through_route_name="南北線"; distance=1.0; duration=2};
  {start_station_name="白金台"; end_station_name="目黒"; go_through_route_name="南北線"; distance=1.3; duration=2};
  {start_station_name="市ヶ谷"; end_station_name="飯田橋"; go_through_route_name="南北線"; distance=1.1 ; duration=2};
  {start_station_name="飯田橋"; end_station_name="後楽園"; go_through_route_name="南北線"; distance=1.4 ; duration=2};
  {start_station_name="後楽園"; end_station_name="東大前"; go_through_route_name="南北線"; distance=1.3 ; duration=3};
  {start_station_name="東大前"; end_station_name="本駒込"; go_through_route_name="南北線"; distance=0.9 ; duration=2};
  {start_station_name="本駒込"; end_station_name="駒込"; go_through_route_name="南北線"; distance=1.4; duration=2};
  {start_station_name="駒込"; end_station_name="西ヶ原"; go_through_route_name="南北線"; distance=1.4; duration=2};
  {start_station_name="西ヶ原"; end_station_name="王子"; go_through_route_name="南北線"; distance=1.0; duration=2};
  {start_station_name="王子"; end_station_name="王子神谷"; go_through_route_name="南北線"; distance=1.2; duration=2};
  {start_station_name="王子神谷"; end_station_name="志茂"; go_through_route_name="南北線"; distance=1.6; duration=3};
  {start_station_name="志茂"; end_station_name="赤羽岩淵"; go_through_route_name="南北線"; distance=1.1; duration=2};
  {start_station_name="西船橋" ; end_station_name="原木中山"; go_through_route_name="東西線"; distance=1.9; duration=3};
  {start_station_name="原木中山"; end_station_name="妙典"; go_through_route_name="東西線"; distance=2.1 ; duration=2};
  {start_station_name="妙典"; end_station_name="行徳"; go_through_route_name="東西線"; distance=1.3 ; duration=2};
  {start_station_name="行徳"; end_station_name="南行徳"; go_through_route_name="東西線"; distance=1.5 ; duration=2};
  {start_station_name="南行徳"; end_station_name="浦安" ; go_through_route_name="東西線"; distance=1.2 ; duration=2};
  {start_station_name="浦安" ; end_station_name="葛西"; go_through_route_name="東西線"; distance=1.9 ; duration=2};
  {start_station_name="葛西"; end_station_name="西葛西"; go_through_route_name="東西線"; distance=1.2 ; duration=2};
  {start_station_name="西葛西"; end_station_name="南砂町"; go_through_route_name="東西線"; distance=2.7 ; duration=2};
  {start_station_name="南砂町"; end_station_name="東陽町"; go_through_route_name="東西線"; distance=1.2 ; duration=2};
  {start_station_name="東陽町"; end_station_name="木場" ; go_through_route_name="東西線"; distance=0.9 ; duration=1};
  {start_station_name="木場"; end_station_name="門前仲町"; go_through_route_name="東西線"; distance=1.1 ; duration=1};
  {start_station_name="門前仲町"; end_station_name="茅場町"; go_through_route_name="東西線"; distance=1.8 ; duration=2};
  {start_station_name="茅場町"; end_station_name="日本橋"; go_through_route_name="東西線"; distance=0.5 ; duration=1};
  {start_station_name="日本橋"; end_station_name="大手町"; go_through_route_name="東西線"; distance=0.8 ; duration=1};
  {start_station_name="大手町"; end_station_name="竹橋"; go_through_route_name="東西線"; distance=1.0; duration=2};
  {start_station_name="竹橋"; end_station_name="九段下"; go_through_route_name="東西線"; distance=1.0; duration=1};
  {start_station_name="九段下"; end_station_name="飯田橋"; go_through_route_name="東西線"; distance=0.7; duration=1};
  {start_station_name="飯田橋"; end_station_name="神楽坂"; go_through_route_name="東西線"; distance=1.2; duration=2};
  {start_station_name="神楽坂"; end_station_name="早稲田"; go_through_route_name="東西線"; distance=1.2; duration=2};
  {start_station_name="早稲田"; end_station_name="高田馬場"; go_through_route_name="東西線"; distance=1.7; duration=3};
  {start_station_name="高田馬場"; end_station_name="落合"; go_through_route_name="東西線"; distance=1.9; duration=3};
  {start_station_name="落合"; end_station_name="中野"; go_through_route_name="東西線"; distance=2.0; duration=3};
  {start_station_name="新木場"; end_station_name="辰巳"; go_through_route_name="有楽町線"; distance=1.5; duration=2};
  {start_station_name="辰巳"; end_station_name="豊洲"; go_through_route_name="有楽町線"; distance=1.7; duration=2};
  {start_station_name="豊洲"; end_station_name="月島"; go_through_route_name="有楽町線"; distance=1.4; duration=2};
  {start_station_name="月島"; end_station_name="新富町"; go_through_route_name="有楽町線"; distance=1.3; duration=2};
  {start_station_name="新富町"; end_station_name="銀座一丁目"; go_through_route_name="有楽町線"; distance=0.7; duration=1};
  {start_station_name="銀座一丁目"; end_station_name="有楽町"; go_through_route_name="有楽町線"; distance=0.5; duration=1};
  {start_station_name="有楽町"; end_station_name="桜田門"; go_through_route_name="有楽町線"; distance=1.0; duration=1};
  {start_station_name="桜田門"; end_station_name="永田町"; go_through_route_name="有楽町線"; distance=0.9; duration=2};
  {start_station_name="永田町"; end_station_name="麹町"; go_through_route_name="有楽町線"; distance=0.9; duration=1};
  {start_station_name="麹町"; end_station_name="市ヶ谷"; go_through_route_name="有楽町線"; distance=0.9; duration=1};
  {start_station_name="市ヶ谷"; end_station_name="飯田橋"; go_through_route_name="有楽町線"; distance=1.1; duration=2};
  {start_station_name="飯田橋"; end_station_name="江戸川橋"; go_through_route_name="有楽町線"; distance=1.6; duration=3};
  {start_station_name="江戸川橋"; end_station_name="護国寺"; go_through_route_name="有楽町線"; distance=1.3; duration=2};
  {start_station_name="護国寺"; end_station_name="東池袋"; go_through_route_name="有楽町線"; distance=1.1; duration=2};
  {start_station_name="東池袋"; end_station_name="池袋"; go_through_route_name="有楽町線"; distance=2.0; duration=2};
  {start_station_name="池袋"; end_station_name="要町"; go_through_route_name="有楽町線"; distance=1.2; duration=2};
  {start_station_name="要町"; end_station_name="千川"; go_through_route_name="有楽町線"; distance=1.0; duration=1};
  {start_station_name="千川"; end_station_name="小竹向原"; go_through_route_name="有楽町線"; distance=1.0; duration=2};
  {start_station_name="小竹向原"; end_station_name="氷川台"; go_through_route_name="有楽町線"; distance=1.5; duration=2};
  {start_station_name="氷川台"; end_station_name="平和台"; go_through_route_name="有楽町線"; distance=1.4; duration=2};
  {start_station_name="平和台"; end_station_name="営団赤塚"; go_through_route_name="有楽町線"; distance=1.8; duration=2};
  {start_station_name="営団赤塚"; end_station_name="営団成増"; go_through_route_name="有楽町線"; distance=1.5; duration=2};
  {start_station_name="営団成増"; end_station_name="和光市"; go_through_route_name="有楽町線"; distance=2.1; duration=3};
]

let rec roma_to_kanji r lst = match lst with
    [] -> ""
  | {kanji = kanji; kana = kana; roma = roma; route_name = route_name;} :: rest ->
    if r = roma then kanji else roma_to_kanji r rest ;;
roma_to_kanji "myogadani" global_station_info_list ;;

let rec get_between_station_distance start_station end_station lst = match lst with
    [] -> infinity
  | {start_station_name = lst_start_station; end_station_name = lst_end_station; go_through_route_name = go_through_route_name; distance = distance; duration = duration;} :: rest ->
    if start_station = lst_start_station && end_station = lst_end_station then distance else
    if start_station = lst_end_station && end_station = lst_start_station then distance else
      get_between_station_distance start_station end_station rest ;;
get_between_station_distance "茗荷谷" "新大塚" global_between_stations_info_list ;;

let display_distance start_roma end_roma =
  let start_kanji = roma_to_kanji start_roma global_station_info_list in
  let end_kanji = roma_to_kanji end_roma global_station_info_list in
  let distance = get_between_station_distance start_kanji end_kanji global_between_stations_info_list in
  if distance = infinity then start_kanji ^ "駅と" ^ end_kanji ^ "駅はつながっていません"
  else start_kanji ^ "駅から" ^ end_kanji ^ "B駅までは" ^ string_of_float distance ^ "kmです" ;;
display_distance "myogadani" "shinotsuka" ;;
display_distance "myogadani" "honkomagome" ;;
